card scroll
aragideti/FlyTicketsBooking pull request #1
Opened 2023-09-24 11:48 UTC by aragideti

2023-09-24 16:31 UTC, slothdeboss requested changes

2023-09-24 16:31 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/HomeScreen.kt
> +        val (hotOfferText, cardSlider, seeAllText, bookFLightText, menuButton, tabSwitcher)
@aragideti I think you need to wrap `createRefs()` into `remember { }` block

2023-09-24 16:31 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/HomeScreen.kt
> +        val items = listOf("One way", "Round", "Multiply")
@aragideti maybe it's better to extract these values into resources or enum?

2023-09-24 16:31 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/HomeScreen.kt
> +    }
@aragideti also if you want to mutate these values I think you need to change from `val` to `var`

2023-09-24 16:31 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/tabs/TabIndicator.kt
> +    modifier: Modifier = Modifier,
@aragideti modifier should be the first parameter with a default value, but if you have any other parameters with no default value, they should be before modifier. In this case the order should be `setSelected, selected, items, modifier`

2023-09-24 16:31 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/tabs/TabIndicator.kt
> +    onClick: (index: Int) -> Unit,
@aragideti same here, please fix the order

2023-09-28 05:44 UTC, igel911 approved these changes

2023-10-01 17:24 UTC, slothdeboss approved these changes

2023-10-08 20:46 UTC, merged