add viewmodel, di (koin)
aragideti/FlyTicketsBooking pull request #4
Opened 2023-11-05 23:53 UTC by aragideti

2023-11-06 12:25 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/tabs/tabScreen/oneway/OneWay.kt
> +    lifecycleOwner: androidx.lifecycle.LifecycleOwner
@aragideti I think there's no need to pass lifecycleOwner as a parameter here, because OneWay is composable and you can get access to lifecyleOwner from here

2023-11-06 12:26 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/tabs/tabScreen/oneway/OneWay.kt
> +    val chosenDate = remember { mutableStateOf(startChooseDateText) }
@aragideti it's better to delegate this to view model

2023-11-06 12:29 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/tabs/tabScreen/oneway/OneWay.kt
> +    }
@aragideti it's better to use collectAsState to convert live data to state and observe changes properly

2023-11-26 18:48 UTC, slothdeboss requested changes

2023-11-26 18:48 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/di/AppModule.kt
> +        viewModel { OneWayViewModel() }
@aragideti as per documentation it's better to use `viewModelOf(::OneWayViewModel)` instead of `viewModel { OneWayViewModel() }`

2023-11-26 18:48 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/tabs/tabScreen/oneway/OneWay.kt
> +private fun AddReturnDate(modifier: Modifier, choose: StateFlow<UiText>) {
@aragideti you don't need to pass flow to the composable. It's better to observe it as state and pass value as a parameter
```
@Composabe
fun YourTopComposable() {
    val choose by viewModel.returnDate.observeAsStateWithLifecycle()
    
    AddReturnDate(modifier = Modifier, choose = choose)
}
```

Here's a [link](https://developer.android.com/jetpack/compose/state-hoisting) to read more about state hoisting

2023-11-26 18:48 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/tabs/tabScreen/oneway/OneWay.kt
> +private fun SmallItemDeparture(modifier: Modifier, choose: StateFlow<UiText>) {
@aragideti same here

2023-11-26 18:48 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/feature/home/tabs/tabScreen/oneway/OneWayViewModel.kt
> +    }
@aragideti let's place all properties at the top of the class and then all methods. It's easier to read this code

2023-11-26 18:48 UTC, slothdeboss commented on app/src/main/java/com/compose/flyticketsbooking/utilities/UiText.kt
> +    }
@aragideti not sure if it's a good idea to place composable here

2023-11-27 01:15 UTC, aragideti commented on app/src/main/java/com/compose/flyticketsbooking/di/AppModule.kt
> +        viewModel { OneWayViewModel() }
done

2023-12-17 20:57 UTC, merged